### PR TITLE
revert to dbchangelog-3.0.xsd

### LINKED ISSUE #461: hot reload and liquibase
Using hot reload, when the master.xml file of liquibase is updated (by adding a db-changelog file for example), it also changes the header from this:

```
http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.0.xsd"
```

to:

```
http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd"
```

Using 3.1, when I start the server I have:

```
Caused by: org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 138; cvc-elt.1: Cannot find the declaration of element 'databaseChangeLog'.
```

If I manually edit the file and switch back to 3.0 it is re-starting fine.

### PR DESCRIPTION
**Pull request by ctamisier**
to fix https://github.com/jhipster/generator-jhipster/issues/461

### CODE REVIEW

**Comment by jmirc** [comment]
Thanks for your PR

**Comment by ctamisier** [comment]
you're welcome, it was the opportunity for me to have a look on jhispter-loader :) that's very nice.

**Comment by jmirc** [comment]
I will release the version 0.11 soon

**Comment by jmirc** [comment]
0.11 has been released. You can update your pom.

**Pull request merged**
